name: CI

on:
  pull_request:
    branches: [main, dev, release]
  push:
    branches: [main, dev, release]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm ci
      - name: Install libgtk-3-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libsoup2.4-dev \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev
      - name: Run ESLint
        run: npm run lint
      - name: Check Prettier formatting
        run: npm run format:check
      - name: Check Rust formatting
        run: npm run tauri:format:check
      - name: Run Rust Clippy
        run: mkdir dist && npm run tauri:lint
